// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OKTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void oK() {
    // Test name: OK
    // Step # | name | target | value
    // 1 | open | /reg/ | 
    driver.get("https://en-gb.facebook.com/reg/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | id=u_0_b_3H | 
    driver.findElement(By.id("u_0_b_3H")).click();
    // 4 | type | id=u_0_b_3H | Deni
    driver.findElement(By.id("u_0_b_3H")).sendKeys("Deni");
    // 5 | click | id=u_0_d_wR | 
    driver.findElement(By.id("u_0_d_wR")).click();
    // 6 | type | id=u_0_d_wR | Sasa
    driver.findElement(By.id("u_0_d_wR")).sendKeys("Sasa");
    // 7 | click | id=u_0_g_7T | 
    driver.findElement(By.id("u_0_g_7T")).click();
    // 8 | type | id=u_0_g_7T | 0895332021434
    driver.findElement(By.id("u_0_g_7T")).sendKeys("0895332021434");
    // 9 | click | id=password_step_input | 
    driver.findElement(By.id("password_step_input")).click();
    // 10 | type | id=password_step_input | hanizaki0406
    driver.findElement(By.id("password_step_input")).sendKeys("hanizaki0406");
    // 11 | click | id=day | 
    driver.findElement(By.id("day")).click();
    // 12 | select | id=day | label=1
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      dropdown.findElement(By.xpath("//option[. = '1']")).click();
    }
    // 13 | click | id=month | 
    driver.findElement(By.id("month")).click();
    // 14 | select | id=month | label=Feb
    {
      WebElement dropdown = driver.findElement(By.id("month"));
      dropdown.findElement(By.xpath("//option[. = 'Feb']")).click();
    }
    // 15 | click | id=year | 
    driver.findElement(By.id("year")).click();
    // 16 | select | id=year | label=1989
    {
      WebElement dropdown = driver.findElement(By.id("year"));
      dropdown.findElement(By.xpath("//option[. = '1989']")).click();
    }
    // 17 | click | id=u_0_4_xD | 
    driver.findElement(By.id("u_0_4_xD")).click();
    // 18 | click | id=u_0_s_Jd | 
    driver.findElement(By.id("u_0_s_Jd")).click();
    // 19 | click | id=u_6_2_TZ | 
    driver.findElement(By.id("u_6_2_TZ")).click();
    // 20 | type | id=code_in_cliff | 33268
    driver.findElement(By.id("code_in_cliff")).sendKeys("33268");
    // 21 | click | id=u_8_4_SS | 
    driver.findElement(By.id("u_8_4_SS")).click();
    // 22 | click | linkText=OK | 
    driver.findElement(By.linkText("OK")).click();
    // 23 | click | css=.xqmdsaz > .x1i10hfl .x9f619 > .x193iq5w > .x1lliihq | 
    driver.findElement(By.cssSelector(".xqmdsaz > .x1i10hfl .x9f619 > .x193iq5w > .x1lliihq")).click();
  }
}
